# Generated by Django 3.0.5 on 2020-07-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0002_product_productfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='files',
        ),
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='ProductFile',
        ),
    ]
