# Generated by Django 3.0.5 on 2020-07-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0004_auto_20200704_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='classes',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_old',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
