# Generated by Django 3.0.5 on 2020-07-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0005_auto_20200704_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_old',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
