# Generated by Django 3.0.5 on 2020-07-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0012_auto_20200705_0216'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='material',
            table='materials',
        ),
    ]
