# Generated by Django 3.0.5 on 2020-07-04 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0013_auto_20200705_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_material', to='shop_site.Material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_product', to='shop_site.Product')),
            ],
            options={
                'db_table': 'products_materials',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(related_name='rel_materials', through='shop_site.ProductMaterial', to='shop_site.Product'),
        ),
    ]
