# Generated by Django 3.0.5 on 2020-07-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0014_auto_20200705_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaterial',
            name='title',
        ),
    ]
