# Generated by Django 3.0.5 on 2020-07-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0015_remove_productmaterial_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorсategory',
            old_name='category',
            new_name='auth_category',
        ),
    ]
