# Generated by Django 3.0.5 on 2020-07-04 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0016_auto_20200705_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorсategory',
            old_name='auth_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='author_category',
        ),
    ]
