# Generated by Django 3.0.5 on 2020-07-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0018_auto_20200705_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(through='shop_site.ProductMaterial', to='shop_site.Material'),
        ),
    ]
