# Generated by Django 3.0.5 on 2020-07-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0019_auto_20200705_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(related_name='rel_materials', through='shop_site.ProductMaterial', to='shop_site.Material'),
        ),
    ]
