# Generated by Django 3.0.8 on 2020-07-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0021_product_is_select_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_select_material',
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('normal', 'Обычный'), ('text_input', 'Набор текста'), ('image_select', 'Выбор изображения')], default='normal', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(blank=True, null=True, related_name='rel_materials', through='shop_site.ProductMaterial', to='shop_site.Material'),
        ),
    ]
