# Generated by Django 3.0.8 on 2020-07-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0022_auto_20200707_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(upload_to='images'),
        ),
    ]
