# Generated by Django 3.0.8 on 2020-07-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0024_auto_20200707_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file_extra1',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file_extra2',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file_extra3',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
