# Generated by Django 3.0.8 on 2020-07-07 21:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0026_auto_20200708_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=tinymce.models.HTMLField(default=2),
            preserve_default=False,
        ),
    ]
