# Generated by Django 3.0.8 on 2020-07-07 21:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0028_auto_20200708_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_return',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
