# Generated by Django 3.0.8 on 2020-07-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0030_auto_20200713_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='author_category',
        ),
    ]
